services:
  stealer-app:
    image: 365-stealer:latest
    environment:
      - ENABLE_IP_WHITELIST=true # Example env var; add Azure creds securely
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
