services:
  stealer-app:
    image: 365-stealer:latest
    environment:
      - ENABLE_IP_WHITELIST=true # Example env var; add Azure creds securely
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
    networks:
      - 365-stealer_default
      - 365-stealers_default
networks:
  365-stealer_default:
    external: true
  365-stealers_default:
    external: true
