version: 

services:
  stealer-app:
    image: 365-stealer:latest
    container_name: 365-stealer
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html  # Optional: for live code edits (remove if not needed)
    restart: unless-stopped  # Optional: auto-restart on failure
