services:
  app:
    container_name: stealer-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - TZ=UTC
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./365-Stealer:/var/www/html
    networks:
      - 365-stealer504_default
networks:
  365-stealer504_default:
    external: true
