version: "3.9"

services:
  my-app:
    build:
      context: .        # folder where Dockerfile and requirements.txt are
      dockerfile: Dockerfile
    image: 365-stealer-app:latest
    ports:
      - "8080:80"       # maps host port 8080 to container port 80
